src/Entity/Adresse.php
<?php

namespace App\Entity;

use App\Repository\AdresseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AdresseRepository::class)]
class Adresse
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $numero = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $adresse = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $code_postal = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $ville = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $pays = null;

    #[ORM\OneToMany(targetEntity: Utilisateur::class, mappedBy: 'adresse')]
    private Collection $idUtilisateur;

    public function __construct()
    {
        $this->idUtilisateur = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumero(): ?string
    {
        return $this->numero;
    }

    public function setNumero(?string $numero): static
    {
        $this->numero = $numero;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(?string $code_postal): static
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(?string $pays): static
    {
        $this->pays = $pays;

        return $this;
    }

    /**
     * @return Collection<int, Utilisateur>
     */
    public function getIdUtilisateur(): Collection
    {
        return $this->idUtilisateur;
    }

    public function addIdUtilisateur(Utilisateur $idUtilisateur): static
    {
        if (!$this->idUtilisateur->contains($idUtilisateur)) {
            $this->idUtilisateur->add($idUtilisateur);
            $idUtilisateur->setAdresse($this);
        }

        return $this;
    }

    public function removeIdUtilisateur(Utilisateur $idUtilisateur): static
    {
        if ($this->idUtilisateur->removeElement($idUtilisateur)) {
            // set the owning side to null (unless already changed)
            if ($idUtilisateur->getAdresse() === $this) {
                $idUtilisateur->setAdresse(null);
            }
        }

        return $this;
    }
}

src/Entity/Candidature.php
<?php

namespace App\Entity;

use App\Repository\CandidatureRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CandidatureRepository::class)]
class Candidature
{
    public const STATUT_PENDING = "An Attente";
    public const STATUT_ACCEPTED = "Retenu";
    public const STATUT_REFUSED = "Ecartée";
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $statut_candidature = self::STATUT_PENDING;

    #[ORM\ManyToOne(inversedBy: 'candidatures')]
    private ?Offre $idOffre = null;

    #[ORM\ManyToOne(inversedBy: 'candidatures')]
    private ?Candidat $idCandidat = null;

    #[ORM\Column(type: "text", nullable: true)]
    private ?string $message = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $CV = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $lettre_de_motivation = null;


    #[ORM\Column(options:['default' => "CURRENT_TIMESTAMP"])]
    private ?\DateTimeImmutable $date_candidature = null;

    public function __construct()
    {
        $this->date_candidature = new \DateTimeImmutable();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStatutCandidature(): ?string
    {
        return $this->statut_candidature;
    }

    public function setStatutCandidature(string $statut_candidature): static
    {
        $this->statut_candidature = $statut_candidature;

        return $this;
    }

    public function getIdOffre(): ?Offre
    {
        return $this->idOffre;
    }

    public function setIdOffre(?Offre $idOffre): static
    {
        $this->idOffre = $idOffre;

        return $this;
    }

    public function getIdCandidat(): ?Candidat
    {
        return $this->idCandidat;
    }

    public function setIdCandidat(?Candidat $idCandidat): static
    {
        $this->idCandidat = $idCandidat;

        return $this;
    }

    public function getDateCandidature(): ?\DateTimeImmutable
    {
        return $this->date_candidature;
    }

    public function setDateCandidature(?\DateTimeImmutable $date_candidature): void
    {
        $this->date_candidature = $date_candidature;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(?string $message): self
    {
        $this->message = $message;
        return $this;
    }

    public function getCV(): ?string
    {
        return $this->CV;
    }

    public function setCV(?string $CV): static
    {
        $this->CV = $CV;

        return $this;
    }

    public function getLettreDeMotivation(): ?string
    {
        return $this->lettre_de_motivation;
    }

    public function setLettreDeMotivation(?string $lettre_de_motivation): static
    {
        $this->lettre_de_motivation = $lettre_de_motivation;

        return $this;
    }
}

src/Entity/Entreprise.php
<?php

namespace App\Entity;

use App\Repository\EntrepriseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: EntrepriseRepository::class)]
#[UniqueEntity("siret", message: "Un compte existe déjà avec ce SIRET")]
class Entreprise
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $siret = null;

    #[ORM\Column(length: 255)]
    private ?string $code_naf = null;

    #[ORM\Column(length: 255)]
    private ?string $telephone = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $telephone2 = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\OneToMany(targetEntity: Offre::class, mappedBy: 'idEntreprise')]
    private Collection $offres;

    #[ORM\OneToMany(targetEntity: Recruteur::class, mappedBy: 'entreprise')]
    private Collection $recruteurs;

    #[ORM\Column]
    private ?bool $isValid = null;

    public function __construct()
    {
        $this->offres = new ArrayCollection();
        $this->recruteurs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getSiret(): ?string
    {
        return $this->siret;
    }

    public function setSiret(string $siret): static
    {
        $this->siret = $siret;

        return $this;
    }

    public function getCodeNaf(): ?string
    {
        return $this->code_naf;
    }

    public function setCodeNaf(string $code_naf): static
    {
        $this->code_naf = $code_naf;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getTelephone2(): ?string
    {
        return $this->telephone2;
    }

    public function setTelephone2(?string $telephone2): static
    {
        $this->telephone2 = $telephone2;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getIdUtilisateur(): ?Utilisateur
    {
        return $this->idUtilisateur;
    }

    public function setIdUtilisateur(?Utilisateur $idUtilisateur): static
    {
        $this->idUtilisateur = $idUtilisateur;

        return $this;
    }

    /**
     * @return Collection<int, Offre>
     */
    public function getOffres(): Collection
    {
        return $this->offres;
    }

    public function addOffre(Offre $offre): static
    {
        if (!$this->offres->contains($offre)) {
            $this->offres->add($offre);
            $offre->setIdEntreprise($this);
        }

        return $this;
    }

    public function removeOffre(Offre $offre): static
    {
        if ($this->offres->removeElement($offre)) {
            // set the owning side to null (unless already changed)
            if ($offre->getIdEntreprise() === $this) {
                $offre->setIdEntreprise(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Recruteur>
     */
    public function getRecruteurs(): Collection
    {
        return $this->recruteurs;
    }

    public function addRecruteur(Recruteur $recruteur): static
    {
        if (!$this->recruteurs->contains($recruteur)) {
            $this->recruteurs->add($recruteur);
            $recruteur->setEntreprise($this);
        }

        return $this;
    }

    public function removeRecruteur(Recruteur $recruteur): static
    {
        if ($this->recruteurs->removeElement($recruteur)) {
            // set the owning side to null (unless already changed)
            if ($recruteur->getEntreprise() === $this) {
                $recruteur->setEntreprise(null);
            }
        }

        return $this;
    }

    public function isIsValid(): ?bool
    {
        return $this->isValid;
    }

    public function setIsValid(bool $isValid): static
    {
        $this->isValid = $isValid;

        return $this;
    }
}

src/Entity/Offre.php
<?php

namespace App\Entity;

use App\Repository\OffreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OffreRepository::class)]
class Offre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $salaire = null;

    #[ORM\Column(length: 255)]
    private ?string $etude_min = null;

    #[ORM\Column(length: 255)]
    private ?string $experience_min = null;

    #[ORM\Column(length: 255)]
    private ?string $type_contrat = null;

    #[ORM\Column(length: 255)]
    private ?string $nb_heure = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $prerequis = null;

    #[ORM\ManyToOne(inversedBy: 'offres')]
    private ?Entreprise $idEntreprise = null;

    #[ORM\OneToMany(targetEntity: Candidature::class, mappedBy: 'idOffre')]
    private Collection $candidatures;

    #[ORM\Column(options:['default' => "CURRENT_TIMESTAMP"])]
    private ?\DateTimeImmutable $date_creation = null;

    public function __construct()
    {
        $this->candidatures = new ArrayCollection();
        $this->date_creation = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getSalaire(): ?string
    {
        return $this->salaire;
    }

    public function setSalaire(?string $salaire): static
    {
        $this->salaire = $salaire;

        return $this;
    }

    public function getEtudeMin(): ?string
    {
        return $this->etude_min;
    }

    public function setEtudeMin(string $etude_min): static
    {
        $this->etude_min = $etude_min;

        return $this;
    }

    public function getExperienceMin(): ?string
    {
        return $this->experience_min;
    }

    public function setExperienceMin(string $experience_min): static
    {
        $this->experience_min = $experience_min;

        return $this;
    }

    public function getTypeContrat(): ?string
    {
        return $this->type_contrat;
    }

    public function setTypeContrat(string $type_contrat): static
    {
        $this->type_contrat = $type_contrat;

        return $this;
    }

    public function getNbHeure(): ?string
    {
        return $this->nb_heure;
    }

    public function setNbHeure(string $nb_heure): static
    {
        $this->nb_heure = $nb_heure;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrerequis(): ?string
    {
        return $this->prerequis;
    }

    public function setPrerequis(string $prerequis): static
    {
        $this->prerequis = $prerequis;

        return $this;
    }

    public function getIdEntreprise(): ?Entreprise
    {
        return $this->idEntreprise;
    }

    public function setIdEntreprise(?Entreprise $idEntreprise): static
    {
        $this->idEntreprise = $idEntreprise;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeImmutable
    {
        return $this->date_creation;
    }

    public function setDateCreation(?\DateTimeImmutable $date_creation): void
    {
        $this->date_creation = $date_creation;
    }


    /**
     * @return Collection<int, Candidature>
     */
    public function getCandidatures(): Collection
    {
        return $this->candidatures;
    }

    public function addCandidature(Candidature $candidature): static
    {
        if (!$this->candidatures->contains($candidature)) {
            $this->candidatures->add($candidature);
            $candidature->setIdOffre($this);
        }

        return $this;
    }

    public function removeCandidature(Candidature $candidature): static
    {
        if ($this->candidatures->removeElement($candidature)) {
            // set the owning side to null (unless already changed)
            if ($candidature->getIdOffre() === $this) {
                $candidature->setIdOffre(null);
            }
        }

        return $this;
    }
}

src/Controller/Entreprise/AccueilController.php
<?php

namespace App\Controller\Entreprise;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class AccueilController extends AbstractController
{

    #[Route('/entreprise/accueil', name: 'accueil_entreprise')]
    public function accueil(AuthenticationUtils $authenticationUtils): Response
    {

        $recruteur = $this->getUser();
        $entreprise = $this->getUser()->getEntreprise();
        $adresse = $this->getUser()->getAdresse();
        $lastOffre = $this->getUser()->getEntreprise()->getOffres()->last();

        $countOffre = $this->getUser()->getEntreprise()->getOffres()->count();
        return $this->render(view: 'entreprise/accueil.html.twig', parameters: [
            'recruteur' => $recruteur,
            'entreprise' => $entreprise,
            'adresse' => $adresse,
            'lastOffre' => $lastOffre,
            'countOffre' => $countOffre
        ]);
    }

}

src/Controller/Entreprise/ContacterCandidatController.php
<?php

namespace App\Controller\Entreprise;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ContacterCandidatController extends AbstractController
{
    #[Route('/contactercandidat', name: 'contactercandidat')]
    public function index(): Response
    {
        return $this->render(view: 'entreprise/contactercandidat.html.twig', parameters: [

        ]);
    }
}

src/Controller/Entreprise/ModifierInformationController.php
<?php

namespace App\Controller\Entreprise;

class ModifierInformationController
{

}

src/Controller/EntrepriseController.php
<?php

namespace App\Controller;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class EntrepriseController extends AbstractController
{
    #[Route('/lesentreprises', name: 'lesentreprises')]
    public function index(): Response
    {
        return $this->render(view: 'touteslesentreprises.html.twig', parameters: [

        ]);
    }
}

templates/entreprise/accueil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil-entreprise{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{asset('assets/css/accueil-entreprise.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
{% endblock %}

{% block body %}

    <main class="flex-shrink-0 corps-blanc">

        <div class="container-fluid mb-4">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 d-flex align-items-center justify-content-center">
                        <h1>{{ entreprise.nom }}</h1>
                    </div>
                </div>
            </div>
        </div>


        <section>
            <div class="container">
                <div class="mb-4 d-flex justify-content-end">
                    <a href="{{ path('cree-offre') }}">
                        <button type="button" class="btn btn-valider btn-dark">Créer une offre</button>
                    </a>
                </div>
                <div class="row mb-5">
                    <div class="col-md-12">
                        <div class="card" id="card-offre">
                            <div class="card-header">
                                <h4 class="card-titre"><i class="fas fa-briefcase me-3"></i>Mes offres</h4>
                            </div>
                            <div class="card-body">
                                <div class="">
                                    <div data-bs-toggle="collapse" data-bs-target="#collapseEnLigne" role="button" aria-expanded="true" aria-controls="collapseEnLigne" class="collapse-toggle">
                                        <span class="number me-2">({{ countOffre }})</span> <span class="choix">Offres publiées</span> <i class="fas fa-chevron-down"></i>
                                    </div>
                                    <div id="collapseEnLigne" class="collapse col-md-12">
                                        <table aria-describedby="offres en ligne" class="table table-hover">
                                            <tr>
                                                <th class="col-md-3">Poste</th>
                                                <th class="col-md-3">Type Contrat</th>
                                                <th class="col-md-3">Date de publication</th>
                                                <th class="col-md-3">Salaire</th>
                                                <th class="col-md-3">Modifier</th>
                                            </tr>
                                            <tr>
                                                <td class="col-md-3">{{ lastOffre.titre }}</td>
                                                <td class="col-md-3">{{ lastOffre.typeContrat }}</td>
                                                <td class="col-md-3">{{ lastOffre.dateCreation|date('d-m-Y') }}</td>
                                                <td class="col-md-3">{{ lastOffre.salaire }} €</td>
                                                <td>
                                                    <a href="#">
                                                        <i class="fas fa-pen" style="color: black;"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer d-flex justify-content-end">
                                <a href="{{ path('afficher-les-offres') }}" class="footer-link">Voir toutes les offres</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row mb-5">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-titre"><i class="fas fa-search me-3"></i>Mes recherches</h4>
                            </div>
                            <div class="card-body">
                                <table class="table table">
                                    <tr>
                                        <td>Nom recherche</td>
                                        <td>Nombre de candidats</td>
                                        <td><a href="#"><i class="fas fa-pen" style="color: black;"></i></a></td>
                                    </tr>
                                </table>
                            </div>
                            <div class="card-footer d-flex justify-content-end">
                                <a href="#" class="footer-link">Voir toutes mes recherches</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row mb-5">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-titre"><i class="fas fa-info-circle me-3"></i>Mon entreprise</h4>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="info mb-10">Société :</div>
                                            <p>
                                                {{ entreprise.nom }} <br>
                                                SIRET : {{ entreprise.siret }} <br>
                                                Code NAF : {{ entreprise.codeNaf }} <br>
                                            </p>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="info mb-10">Adresse :</div>
                                            <p>
                                                {{ adresse.numero }} {{ adresse.adresse }} <br>
                                                {{ adresse.codePostal }} {{ adresse.ville }} <br>
                                                {{ adresse.pays }}
                                            </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </main>


{% endblock %}

templates/entreprise/gererlesOffre.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gérer les offres{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('assets/css/gererlesoffres.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
{% endblock %}

{% block body %}

    <div class="container-fluid mb-4 bande">
        <div class="container-fluid mb-4">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 d-flex align-items-center justify-content-center">
                        <h1>{{ entreprise.nom }}</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <section>


    </section>
        <div class="container">
            <div class="mb-4 d-flex justify-content-start mt-3">
                <a href="{{ path('accueil_entreprise') }}">
                    <button type="button" class="btn btn-valider btn-dark">Retour</button>
                </a>
            </div>
            <div class=" text-start">
                <div class="" style="text-decoration: underline; color: black;">
                    <h3>Gérer vos offres</h3>
                </div>
            </div>

            <div class="mb-4 d-flex justify-content-end">
                <a href="{{ path('cree-offre') }}">
                    <button type="button" class="btn btn-valider btn-dark">Créer une offre</button>
                </a>
            </div>

            <div class="col-12">
                <div class="table-responsive shadow p-3">
                    <table class="table table-bordered table-hover">
                        <thead class="thead-dark">
                            <tr>
                                <th>N°</th>
                                <th>Titre</th>
                                <th>Salaire</th>
                                <th>Type de contrat</th>
                                <th>Candidatures à traiter</th>
                                <th>Publié le</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for offre in offres %}
                                <tr>
                                    <td>
                                        <a href="{{ path('gerer_une_offre', {'id': offre.id}) }}">
                                            {{ loop.index }}
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{{ path('gerer_une_offre', {'id': offre.id}) }}">
                                            {{ offre.titre }}
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{{ path('gerer_une_offre', {'id': offre.id}) }}">
                                            {{ offre.salaire }}
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{{ path('gerer_une_offre', {'id': offre.id}) }}">
                                            {{ offre.typeContrat }}
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{{ path('gerer_une_offre', {'id': offre.id}) }}">
                                            {{ offre.candidatures|filter(c => c.statutCandidature == constant('App\\Entity\\Candidature::STATUT_PENDING') )|length}}
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{{ path('gerer_une_offre', {'id': offre.id}) }}">
                                            {{ offre.dateCreation|date("d/m/Y") }}
                                        </a>
                                    </td>
                                </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

{% endblock %}

templates/entreprise/gererunecandidature.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gérer une candidature{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('assets/css/gerercandidature.css') }}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
{% endblock %}

{% block body %}

    <div class="container-fluid mb-4 bande">
        <div class="container-fluid mb-4">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 d-flex align-items-center justify-content-center">
                        <h1>{{ entreprise.nom }}</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <section>
        <div class="container">
            <div class="mb-4 d-flex justify-content-start mt-3">
                <a href="{{ path('gerer_une_offre', {'id': candidature.idOffre.id} )}}">
                    <button type="button" class="btn btn-valider btn-dark">Retour</button>
                </a>
            </div>
            <div class=" text-start">
                <div class="" style=" color: black;">
                    <h4>{{ candidature.idOffre.titre }}</h4>
                </div>
            </div>

            <div class="mb-4 d-flex justify-content-end">
                <a href="{{ path('refuser-une-candidature', {'id': candidature.id}) }}">
                    <button type="button" class="btn btn-annuler btn-dark me-4">Ecarter ce candidat</button>
                </a>
                <a href="{{ path('accepter-une-candidature', {'id': candidature.id}) }}">
                    <button type="button" class="btn btn-valider btn-dark">Retenir ce candidat</button>
                </a>


            </div>

            <div class="offre-box">
                <div class="offre-info">
                    <h5>{{ candidature.idCandidat.nom }}</h5>
                    <p class="mb-0">{{ candidature.idCandidat.telephone }}</p>
                    <p class="mb-0">{{ candidature.idCandidat.email }}</p>
                </div>
                <div class="icons">
                    <p>{{ candidature.dateCandidature|date("d/m/Y") }}</p>
                    <p><a class="text-decoration-none" href="#"><i class="fas fa-download"></i><span class="ms-2">Télécharger le Cv</span></a></p>
                    <p><a class="text-decoration-none" href="#"><i class="fas fa-download"></i><span class="ms-2">Télécharger Lettre de Motivation</span></a></p>
                </div>
            </div>

            <div class="mb-4 d-flex justify-content-end mt-3">
                <button type="button" class="btn btn-valider btn-dark">Contacter ce candidat</button>
            </div>
        </div>
    </section>


{% endblock %}