src/Entity/Candidat.php
<?php

namespace App\Entity;

use App\Repository\CandidatRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CandidatRepository::class)]
class Candidat extends Utilisateur
{
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $telephone = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $CV = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $lettre_de_motivation = null;

    #[ORM\OneToMany(targetEntity: Candidature::class, mappedBy: 'idCandidat')]
    private Collection $candidatures;

    public function __construct()
    {
        $this->candidatures = new ArrayCollection();
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getCV(): ?string
    {
        return $this->CV;
    }

    public function setCV(?string $CV): static
    {
        $this->CV = $CV;

        return $this;
    }

    public function getLettreDeMotivation(): ?string
    {
        return $this->lettre_de_motivation;
    }

    public function setLettreDeMotivation(?string $lettre_de_motivation): static
    {
        $this->lettre_de_motivation = $lettre_de_motivation;

        return $this;
    }


    /**
     * @return Collection<int, Candidature>
     */
    public function getCandidatures(): Collection
    {
        return $this->candidatures;
    }

    public function addCandidature(Candidature $candidature): static
    {
        if (!$this->candidatures->contains($candidature)) {
            $this->candidatures->add($candidature);
            $candidature->setIdCandidat($this);
        }

        return $this;
    }

    public function removeCandidature(Candidature $candidature): static
    {
        if ($this->candidatures->removeElement($candidature)) {
            // set the owning side to null (unless already changed)
            if ($candidature->getIdCandidat() === $this) {
                $candidature->setIdCandidat(null);
            }
        }

        return $this;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_CANDIDAT';

        return array_unique($roles);
    }
}

src/Entity/Candidature.php
<?php

namespace App\Entity;

use App\Repository\CandidatureRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CandidatureRepository::class)]
class Candidature
{
    public const STATUT_PENDING = "An Attente";
    public const STATUT_ACCEPTED = "Retenu";
    public const STATUT_REFUSED = "Ecartée";
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $statut_candidature = self::STATUT_PENDING;

    #[ORM\ManyToOne(inversedBy: 'candidatures')]
    private ?Offre $idOffre = null;

    #[ORM\ManyToOne(inversedBy: 'candidatures')]
    private ?Candidat $idCandidat = null;

    #[ORM\Column(type: "text", nullable: true)]
    private ?string $message = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $CV = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $lettre_de_motivation = null;


    #[ORM\Column(options:['default' => "CURRENT_TIMESTAMP"])]
    private ?\DateTimeImmutable $date_candidature = null;

    public function __construct()
    {
        $this->date_candidature = new \DateTimeImmutable();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStatutCandidature(): ?string
    {
        return $this->statut_candidature;
    }

    public function setStatutCandidature(string $statut_candidature): static
    {
        $this->statut_candidature = $statut_candidature;

        return $this;
    }

    public function getIdOffre(): ?Offre
    {
        return $this->idOffre;
    }

    public function setIdOffre(?Offre $idOffre): static
    {
        $this->idOffre = $idOffre;

        return $this;
    }

    public function getIdCandidat(): ?Candidat
    {
        return $this->idCandidat;
    }

    public function setIdCandidat(?Candidat $idCandidat): static
    {
        $this->idCandidat = $idCandidat;

        return $this;
    }

    public function getDateCandidature(): ?\DateTimeImmutable
    {
        return $this->date_candidature;
    }

    public function setDateCandidature(?\DateTimeImmutable $date_candidature): void
    {
        $this->date_candidature = $date_candidature;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(?string $message): self
    {
        $this->message = $message;
        return $this;
    }

    public function getCV(): ?string
    {
        return $this->CV;
    }

    public function setCV(?string $CV): static
    {
        $this->CV = $CV;

        return $this;
    }

    public function getLettreDeMotivation(): ?string
    {
        return $this->lettre_de_motivation;
    }

    public function setLettreDeMotivation(?string $lettre_de_motivation): static
    {
        $this->lettre_de_motivation = $lettre_de_motivation;

        return $this;
    }
}

src/Entity/Offre.php
<?php

namespace App\Entity;

use App\Repository\OffreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OffreRepository::class)]
class Offre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $salaire = null;

    #[ORM\Column(length: 255)]
    private ?string $etude_min = null;

    #[ORM\Column(length: 255)]
    private ?string $experience_min = null;

    #[ORM\Column(length: 255)]
    private ?string $type_contrat = null;

    #[ORM\Column(length: 255)]
    private ?string $nb_heure = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $prerequis = null;

    #[ORM\ManyToOne(inversedBy: 'offres')]
    private ?Entreprise $idEntreprise = null;

    #[ORM\OneToMany(targetEntity: Candidature::class, mappedBy: 'idOffre')]
    private Collection $candidatures;

    #[ORM\Column(options:['default' => "CURRENT_TIMESTAMP"])]
    private ?\DateTimeImmutable $date_creation = null;

    public function __construct()
    {
        $this->candidatures = new ArrayCollection();
        $this->date_creation = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getSalaire(): ?string
    {
        return $this->salaire;
    }

    public function setSalaire(?string $salaire): static
    {
        $this->salaire = $salaire;

        return $this;
    }

    public function getEtudeMin(): ?string
    {
        return $this->etude_min;
    }

    public function setEtudeMin(string $etude_min): static
    {
        $this->etude_min = $etude_min;

        return $this;
    }

    public function getExperienceMin(): ?string
    {
        return $this->experience_min;
    }

    public function setExperienceMin(string $experience_min): static
    {
        $this->experience_min = $experience_min;

        return $this;
    }

    public function getTypeContrat(): ?string
    {
        return $this->type_contrat;
    }

    public function setTypeContrat(string $type_contrat): static
    {
        $this->type_contrat = $type_contrat;

        return $this;
    }

    public function getNbHeure(): ?string
    {
        return $this->nb_heure;
    }

    public function setNbHeure(string $nb_heure): static
    {
        $this->nb_heure = $nb_heure;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrerequis(): ?string
    {
        return $this->prerequis;
    }

    public function setPrerequis(string $prerequis): static
    {
        $this->prerequis = $prerequis;

        return $this;
    }

    public function getIdEntreprise(): ?Entreprise
    {
        return $this->idEntreprise;
    }

    public function setIdEntreprise(?Entreprise $idEntreprise): static
    {
        $this->idEntreprise = $idEntreprise;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeImmutable
    {
        return $this->date_creation;
    }

    public function setDateCreation(?\DateTimeImmutable $date_creation): void
    {
        $this->date_creation = $date_creation;
    }


    /**
     * @return Collection<int, Candidature>
     */
    public function getCandidatures(): Collection
    {
        return $this->candidatures;
    }

    public function addCandidature(Candidature $candidature): static
    {
        if (!$this->candidatures->contains($candidature)) {
            $this->candidatures->add($candidature);
            $candidature->setIdOffre($this);
        }

        return $this;
    }

    public function removeCandidature(Candidature $candidature): static
    {
        if ($this->candidatures->removeElement($candidature)) {
            // set the owning side to null (unless already changed)
            if ($candidature->getIdOffre() === $this) {
                $candidature->setIdOffre(null);
            }
        }

        return $this;
    }
}

src/Controller/Candidat/AccueilController.php
<?php

namespace App\Controller\Candidat;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;



class AccueilController extends AbstractController
{
    #[Route('/accueil_candidat', name: 'accueil_candidat')]
    public function index(): Response
    {
        return $this->render('candidat/accueil.html.twig', [

        ]);
    }
}

src/Controller/Candidat/CVetLettreController.php
<?php

namespace App\Controller\Candidat;

use App\Service\CandidatVerifier;
use App\Service\CvManager;
use App\Entity\Candidat;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class CVetLettreController extends AbstractController
{
    private $cvManager;
    private $candidatVerifier;

    public function __construct(CvManager $cvManager , CandidatVerifier $candidatVerifier)
    {
        $this->cvManager = $cvManager;
        $this->candidatVerifier = $candidatVerifier;
    }

    #[Route('/cv', name: 'app_cv')]
    public function index(): Response
    {
        $candidat = $this->getUser();
        $this->candidatVerifier->estCandidat($candidat);

        return $this->render('candidat\CVetLettre.html.twig', [
            'candidat' => $candidat,
        ]);
    }

    #[Route('/cv/modifier', name: 'modifier_cv')]
    public function modifierCV(Request $request , EntityManagerInterface $entityManager): Response
    {
        // Vérifier si le candidat est connecté
        $candidat = $this->getUser();
        $this->candidatVerifier->estCandidat($candidat);

        $cvFile = $request->files->get('cv');
        if ($candidat->getCv()) {
            // Supprimer le fichier du CV précédent
            $cvPath = $this->getParameter('candidat_cv') . '/' . $candidat->getCv();
            if (file_exists($cvPath)) {
                unlink($cvPath);
            }
        }
        $cvFileName = $this->cvManager->moveUploadedFile($cvFile, $this->getParameter('candidat_cv'));
        $candidat->setCv($cvFileName);

        $entityManager->persist($candidat);
        $entityManager->flush();

        return $this->redirectToRoute('app_cv');
    }

    #[Route('/lettre_motivation/modifier', name: 'modifier_lettre_motivation')]
    public function modifierLettreMotivation(Request $request , EntityManagerInterface $entityManager): Response
    {
        // Vérifier si le candidat est connecté
        $candidat = $this->getUser();
        $this->candidatVerifier->estCandidat($candidat);

        $lmFile = $request->files->get('lettre_motivation');

        if ($candidat->getLettreDeMotivation()) {
            $lmPath = $this->getParameter('candidat_lm') . '/' . $candidat->getLettreDeMotivation();
            if (file_exists($lmPath)) {
                unlink($lmPath);
            }
        }
        $lmFileName = $this->cvManager->moveUploadedFile($lmFile, $this->getParameter('candidat_lm'));
        $candidat->setLettreDeMotivation($lmFileName);

        $entityManager->persist($candidat);
        $entityManager->flush();

        return $this->redirectToRoute('app_cv');
    }

    
}

src/Controller/Candidat/ConfirmationCvController.php
<?php

namespace App\Controller\Candidat;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class ConfirmationCvController extends AbstractController
{
    #[Route('/confirmation', name: 'app_confirmation')]
    public function index(): Response
    {
        return $this->render('candidat\confirmationCv.html.twig', [

        ]);
    }
}

src/Controller/Candidat/DetailCandidatureController.php
<?php

namespace App\Controller\Candidat;

use App\Entity\Candidat;
use App\Entity\Candidature;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class DetailCandidatureController extends AbstractController
{

    #[Route('/candidatures/{id}', name: 'candidature_details')]
    public function index(int $id , EntityManagerInterface $entityManager ): Response
    {
        $candidature = $entityManager->getRepository(Candidature::class)->find($id);
        
        return $this->render('candidat\detailCandidature.html.twig', [
            'candidature' => $candidature,
        ]);
    }
}

src/Controller/Candidat/GererCandidatreController.php
<?php

namespace App\Controller\Candidat;

class GererCandidatreController
{

}

src/Controller/Candidat/InscriptionController.php
<?php

namespace App\Controller\Candidat;

use App\Entity\Adresse;
use App\Entity\Candidat;
use App\Form\CandidatType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

class InscriptionController extends AbstractController
{

    private $passwordHasher;

    public function __construct(UserPasswordHasherInterface $passwordHasher) {
        $this->passwordHasher = $passwordHasher;
    }

    #[Route('/inscription-candidat', name: 'inscription-candidat')]
    public function inscription(Request $request, EntityManagerInterface $em): Response
    {
        $candidat = new Candidat();
        $form = $this->createForm(CandidatType::class,$candidat);

        if ($request->isMethod('POST')) {
            $allValues = $request->request->all();
            $form->submit($allValues[$form->getName()]);

            if ($form->isSubmitted() && $form->isValid()) {

            /** @var Candidat $candidat */

                $candidat = $form->getData();

                $hashedPassword = $this->passwordHasher->hashPassword(
                    $candidat,
                    $candidat->getPassword()
                );
                $candidat->setPassword($hashedPassword);

                $candidat->setDateInscription(new \DateTimeImmutable());

                $candidat->setRoles(['ROLE_CANDIDAT']);

                $em->persist($candidat);
                $em->flush();

                $this->addFlash(
                    'notice',
                    'Vous êtes bien inscrit, veuillez vous connecter pour accéder à votre espace.'
                );

                return $this->redirectToRoute('connexion');
            }
        }

        return $this->render(view: 'candidat/inscription.html.twig', parameters: [
            'form' => $form
        ]);
    }
}

src/Controller/Candidat/ModifierInformationController.php
<?php

namespace App\Controller\Candidat;

class ModifierInformationController
{

}

src/Controller/candidat/DetailCandidatureController.php
<?php

namespace App\Controller\candidat;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

 
class DetailCandidatureController extends AbstractController
{

    #[Route('/detailC', name: 'app_detailCandidature')] 
    public function index(): Response
    {
        return $this->render('candidat\detailCandidature.html.twig', [
            
        ]);
    }
}

templates/candidat/CVetLettre.html.twig
{% extends 'base.html.twig' %}

{% block title %}ESA{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('assets/css/cvetlettreCandidat.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
{% endblock %}

{% block body %}


    <div class="col mx-auto text-center shadow">
        <div class="p-3" style="text-decoration: underline; color: red;">
            <h2>Consulter vos documents </h2>
        </div>
    </div>

    <br><br>

    <div class="container">
        <div class="shadow-lg p-3 mb-5 bg-white rounded">
            <div class="row gx-5">
                <div class="col-md-6">
                    <div class="p-4 mb-4 bg-white rounded shadow h-100 w-100">
                        <h4 class="text-center">Votre CV</h4>
                        {% if candidat.cv %}
                            <a href="{{ asset('fichiers/candidat/cv/' ~ candidat.cv) }}" target="_blank" class="pdf-link">
                                <i class="fas fa-file-pdf pdf-icon"></i> Voir le CV
                            </a>
                        {% else %}
                            <p>Aucun CV disponible</p>
                        {% endif %}
                        <form method="post" action="{{ path('modifier_cv') }}" enctype="multipart/form-data">
                            <div class="d-grid gap-2">
                                <input type="file" name="cv" class="btn btn-secondary form-control " accept=".pdf, .doc, .docx" />
                                <button class="btn btn-annuler" type="submit">Modifier</button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="p-4 mb-4 bg-white rounded shadow h-100 w-100">
                        <h4 class="text-center">Votre Lettre de Motivation</h4>
                        {% if candidat.lettreDeMotivation %}
                            <a href="{{ asset('fichiers/candidat/lm/' ~ candidat.lettreDeMotivation) }}" target="_blank" class="pdf-link">
                                <i class="fas fa-file-pdf pdf-icon"></i> Voir la lettre de motivation
                            </a>
                        {% else %}
                            <p>Aucune Lettre disponible</p>
                        {% endif %}
                        <form method="post" action="{{ path('modifier_lettre_motivation') }}" enctype="multipart/form-data">
                            <div class="d-grid gap-2">
                                <input type="file" name="lettre_motivation"class="btn btn-secondary form-control" accept=".pdf, .doc, .docx" />
                                <button class="btn btn-annuler" type="submit">Modifier</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>




{% endblock %}

templates/candidat/acceuil.html.twig
{% extends 'base.html.twig' %}

{% block title %}ESA{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('assets/css/acceuil_candidat.css') }}">
{% endblock %}


{% block body %}

    <div class="container text-center">
        <h1 class="mt-5 text-danger">Accueil</h1><br><br>
    </div>

    <div class="container">
        <div class="row g-2">
            <div class="col-md-6">
                <div class="card shadow">
                    <div class="card-body p-3">
                        <a href="#" class="pages d-block text-center text-danger">Mes recherches</a><br>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris magna quam, varius eget urna rutrum, 
                            ultrices lacinia augue. Vestibulum pharetra nibh ipsum, in interdum nunc ultrices id. Cras bibendum lobortis 
                            magna, vitae consequat metus mollis et. Mauris at sodales eros. Vivamus a dui neque. Donec porta, nisi eget
                            mollis iaculis, mauris neque pharetra nisl, id semper est odio ut erat. Aliquam pulvinar congue metus, 
                            aliquet sodales lectus dictum quis. Suspendisse imperdiet leo arcu, id pellentesque mauris placerat ac. 
                            Quisque ultricies consectetur risus, at vulputate quam convallis vel.
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card shadow">
                    <div class="card-body p-3">
                    <a href="#" class="pages d-block text-center text-danger">Favoris</a><br>
                    <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris magna quam, varius eget urna rutrum, 
                            ultrices lacinia augue. Vestibulum pharetra nibh ipsum, in interdum nunc ultrices id. Cras bibendum lobortis 
                            magna, vitae consequat metus mollis et. Mauris at sodales eros. Vivamus a dui neque. Donec porta, nisi eget
                            mollis iaculis, mauris neque pharetra nisl, id semper est odio ut erat. Aliquam pulvinar congue metus, 
                            aliquet sodales lectus dictum quis. Suspendisse imperdiet leo arcu, id pellentesque mauris placerat ac. 
                            Quisque ultricies consectetur risus, at vulputate quam convallis vel.
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card shadow">
                    <div class="card-body p-3">
                        <a href="#" class="pages d-block text-center text-danger">Mes candidatures</a><br>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris magna quam, varius eget urna rutrum, 
                            ultrices lacinia augue. Vestibulum pharetra nibh ipsum, in interdum nunc ultrices id. Cras bibendum lobortis 
                            magna, vitae consequat metus mollis et. Mauris at sodales eros. Vivamus a dui neque. Donec porta, nisi eget
                            mollis iaculis, mauris neque pharetra nisl, id semper est odio ut erat. Aliquam pulvinar congue metus, 
                            aliquet sodales lectus dictum quis. Suspendisse imperdiet leo arcu, id pellentesque mauris placerat ac. 
                            Quisque ultricies consectetur risus, at vulputate quam convallis vel.
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card shadow">
                    <div class="card-body p-3">
                    <a href="#" class="pages d-block text-center text-danger">Mes CV et lettres de motivations</a><br>
                    <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris magna quam, varius eget urna rutrum, 
                            ultrices lacinia augue. Vestibulum pharetra nibh ipsum, in interdum nunc ultrices id. Cras bibendum lobortis 
                            magna, vitae consequat metus mollis et. Mauris at sodales eros. Vivamus a dui neque. Donec porta, nisi eget
                            mollis iaculis, mauris neque pharetra nisl, id semper est odio ut erat. Aliquam pulvinar congue metus, 
                            aliquet sodales lectus dictum quis. Suspendisse imperdiet leo arcu, id pellentesque mauris placerat ac. 
                            Quisque ultricies consectetur risus, at vulputate quam convallis vel.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/candidat/detailCandidature.html.twig
{% extends 'base.html.twig' %}

{% block title %}ESA{% endblock %}


{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('assets\css\detailC_candidat.css') }}">
{% endblock %}


{% block body %}


    <div class="container-fluid py-3">
        <div class="row align-items-center">
            <div class="col text-right">
				<a href="{{ path('app_candidatures') }}" class="btn btn-primary return-button btn-annuler">Retour vers les candidatures</a>
			</div>
        </div>
    </div>


    <div class="row justify-content-center mt-4">
        <div class="col-auto text-center">
            <h2 style="text-decoration: underline; color:red;">Détail de la candidature</h2>
        </div>
    </div>

    <Br>
    <div class="container amber-bg shadow">
        <div class="row justify-content-center">
            <div class="col-md-10">
                </Br>
                <h4 style="text-decoration: underline;">VOTRE CANDIDATURE</h4>
                <p><strong>Date d'envoi de la candidature :</strong> {{candidature.dateCandidature|date('d/m/Y')}}</p>

                <hr><br>

                <h4 style="text-decoration: underline;">RAPPEL DE L'OFFRE SÉLECTIONNÉE</h4>
                <ul class="list-unstyled">
                    <li><strong>Titre du poste :</strong> {{candidature.idOffre.titre}} </li>
                    <li><strong>Société :</strong> {{candidature.idOffre.idEntreprise.nom}} </li>
                    <li><strong>Type de contrat :</strong> {{candidature.idOffre.typeContrat}}</li>
                    <li><strong>Salaire :</strong> {{candidature.idOffre.salaire}}€ brut annuel</li>
                    <li><strong>Expérience :</strong> {{candidature.idOffre.experienceMin}} an(s)</li>
                </ul>

                <hr><br>

                <h4 style="text-decoration: underline;">DÉTAIL DE L'OFFRE</h4>
                <p>{{candidature.idOffre.description}}</p>
                <p>{{candidature.idOffre.prerequis}}</p>
                <hr><br>

                <h4 style="text-decoration: underline;">RAPPEL DU DOSSIER DE CANDIDATURE ADRESSÉ</h4>
                <ul class="list-unstyled">
                    <li><strong>CV attaché :</strong> <a href="{{ asset('fichiers/candidature/cv/' ~ candidature.cv) }}">CV</a></li>
                    {% if candidature.lettreDeMotivation %}
                    <li><strong>LM attaché :</strong> <a href="{{ asset('fichiers/candidature/cv/' ~ candidature.lettreDeMotivation) }}">Lettre de Motivation</a></li>
                    {% endif %} 
                </ul>
            </div>
        </div>
    </div>
    </Br></Br>








{% endblock %}